export default [
  [
    'sounds/DiceDrums1.wav',
    'sounds/DiceDrums2.wav',
    'sounds/DiceDrums3.wav',
    'sounds/DiceDrums4.wav',
    'sounds/DiceDrums5.wav',
    'sounds/DiceDrums6.wav',
  ],
  [
    'sounds/DiceLead1.wav',
    'sounds/DiceLead2.wav',
    'sounds/DiceLead3.wav',
    'sounds/DiceLead4.wav',
    'sounds/DiceLead5.wav',
    'sounds/DiceLead6.wav',
  ],
  [
    'sounds/DiceRhythm1.wav',
    'sounds/DiceRhythm2.wav',
    'sounds/DiceRhythm3.wav',
    'sounds/DiceRhythm4.wav',
    'sounds/DiceRhythm5.wav',
    'sounds/DiceRhythm6.wav',
  ],
];