export default [
  [
    'sounds/dice/Drums1.wav',
    'sounds/dice/Drums2.wav',
    'sounds/dice/Drums3.wav',
    'sounds/dice/Drums4.wav',
    'sounds/dice/Drums5.wav',
    'sounds/dice/Drums6.wav',
  ],
  [
    'sounds/dice/Lead1.wav',
    'sounds/dice/Lead2.wav',
    'sounds/dice/Lead3.wav',
    'sounds/dice/Lead4.wav',
    'sounds/dice/Lead5.wav',
    'sounds/dice/Lead6.wav',
  ],
  [
    'sounds/dice/Rhythm1.wav',
    'sounds/dice/Rhythm2.wav',
    'sounds/dice/Rhythm3.wav',
    'sounds/dice/Rhythm4.wav',
    'sounds/dice/Rhythm5.wav',
    'sounds/dice/Rhythm6.wav',
  ],
];